server:
  port: 8083

spring:
  profiles:
    active: prod

---

# Default configuration

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  application:
    name: schedlr-api-integration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Development profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/schedlr
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Production profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://schedlr-aws.cvu48ycmk8x0.ap-southeast-2.rds.amazonaws.com:3306/schedlr
    username: root
    password: schedlr10
    driver-class-name: com.mysql.cj.jdbc.Driver